FROM mcr.microsoft.com/windows/nanoserver:1809
RUN curl -L -o C:\ProgramData\kubernetes-node-windows-amd64.tar.gz https://dl.k8s.io/v1.17.4/kubernetes-node-windows-amd64.tar.gz
RUN curl -L -o C:\ProgramData\flannel-windows-amd64.tar.gz https://github.com/coreos/flannel/releases/download/v0.12.0/flannel-v0.12.0-windows-amd64.tar.gz 
