FROM alpine
RUN wget -O /kubernetes-node-windows-amd64.tar.gz https://dl.k8s.io/RELEASE_VERSION/kubernetes-node-windows-amd64.tar.gz
RUN wget -O /flannel-windows-amd64.tar.gz https://github.com/coreos/flannel/releases/download/v0.12.0/flannel-v0.12.0-windows-amd64.tar.gz
RUN wget -O /cni-plugins-windows-amd64.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-windows-amd64-v0.8.5.tgz
