FROM alpine
RUN wget -O /kubernetes-node-windows-amd64.tar.gz https://dl.k8s.io/v1.15.10/kubernetes-node-windows-amd64.tar.gz
RUN wget -O /flannel-windows-amd64.tar.gz https://github.com/coreos/flannel/releases/download/v0.11.0/flannel-v0.11.0-windows-amd64.tar.gz
